yaml change

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,6 +22,13 @@ jobs:
 
       - name: Build with Maven
         run: mvn clean package -DskipTests
+      - name: Verify Build Output
+        run: |
+          ls -lh target/
+          if [ ! -f target/EduSched-0.0.1-SNAPSHOT.jar ]; then
+            echo "Error: JAR file not found!"
+            exit 1
+          fi
         
       - name: Aws login
         uses: aws-actions/configure-aws-credentials@v4
